#!/usr/bin/env python3
"""Fuzzy matcher auto-expansion from HITL corrections.

Analyzes reviewed utterances where the fuzzy matcher failed but a human
provided the correct intent. Extracts new keyword candidates from these
transcripts and suggests additions to the KEYWORD_MAP.

Usage:
    python -m voice.training.matcher_expansion [--apply]
"""

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path

AUDIO_BASE_DIR = Path.home() / ".eye_test_audio"
FUZZY_MATCHER_PATH = Path(__file__).resolve().parent.parent / "fuzzy_matcher.py"


def load_corrections():
    """Load utterances where the matcher was wrong and a human corrected it."""
    corrections = []
    if not AUDIO_BASE_DIR.exists():
        return corrections

    for date_dir in sorted(AUDIO_BASE_DIR.iterdir()):
        if not date_dir.is_dir() or date_dir.name.startswith(".") or date_dir.name.startswith("_"):
            continue
        for sess_dir in sorted(date_dir.iterdir()):
            manifest = sess_dir / "manifest.jsonl"
            if not manifest.exists():
                continue
            with open(manifest, "r") as f:
                for line in f:
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        utt = json.loads(line)
                    except json.JSONDecodeError:
                        continue

                    if not utt.get("reviewed") or utt.get("is_garbage"):
                        continue

                    correct = utt.get("correct_option")
                    matched = utt.get("matched_option")
                    transcript = utt.get("transcript_whisper", "").strip().lower()

                    if not transcript or not correct:
                        continue

                    # Case 1: matcher returned wrong answer
                    if matched and matched != correct:
                        corrections.append({
                            "transcript": transcript,
                            "response_type": utt.get("response_type", ""),
                            "wrong_match": matched,
                            "correct_option": correct,
                        })
                    # Case 2: matcher returned nothing (no match)
                    elif not matched:
                        corrections.append({
                            "transcript": transcript,
                            "response_type": utt.get("response_type", ""),
                            "wrong_match": None,
                            "correct_option": correct,
                        })

    return corrections


def generate_suggestions(corrections):
    """Generate keyword suggestions from corrections.

    Groups corrections by (response_type, correct_option) and extracts
    the most common transcript phrases as keyword candidates.
    """
    # Group: (response_type, correct_option) -> list of transcripts
    groups = defaultdict(list)
    for c in corrections:
        key = (c["response_type"], c["correct_option"])
        groups[key].append(c["transcript"])

    suggestions = []
    for (response_type, option), transcripts in sorted(groups.items()):
        # Deduplicate and count
        phrase_counts = defaultdict(int)
        for t in transcripts:
            # Normalize
            t = t.strip().lower()
            if t:
                phrase_counts[t] += 1

        # Sort by frequency
        ranked = sorted(phrase_counts.items(), key=lambda x: -x[1])

        for phrase, count in ranked:
            suggestions.append({
                "response_type": response_type,
                "option": option,
                "phrase": phrase,
                "count": count,
            })

    return suggestions


def print_suggestions(suggestions):
    """Pretty-print suggestions."""
    if not suggestions:
        print("No suggestions — matcher is working well or not enough corrections yet.")
        return

    print(f"Found {len(suggestions)} keyword candidates from corrections:\n")

    current_rt = None
    for s in suggestions:
        if s["response_type"] != current_rt:
            current_rt = s["response_type"]
            print(f"\n  [{current_rt}]")
        print(f"    {s['option']:>15} ← \"{s['phrase']}\"  (seen {s['count']}x)")


def generate_code_patch(suggestions):
    """Generate a Python code snippet to add to fuzzy_matcher.py KEYWORD_MAP."""
    if not suggestions:
        return ""

    lines = ["# === AUTO-GENERATED KEYWORD ADDITIONS ===",
             "# From HITL corrections. Review before applying.",
             "# Generated by: python -m voice.training.matcher_expansion",
             ""]

    by_rt = defaultdict(lambda: defaultdict(list))
    for s in suggestions:
        by_rt[s["response_type"]][s["option"]].append(s["phrase"])

    for rt in sorted(by_rt):
        lines.append(f"# {rt}:")
        for option in sorted(by_rt[rt]):
            phrases = by_rt[rt][option]
            phrases_str = ", ".join(f'"{p}"' for p in phrases)
            lines.append(f"#   {option}: [{phrases_str}]")
        lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Expand fuzzy matcher from HITL corrections")
    parser.add_argument("--apply", action="store_true",
                        help="Write suggestions to a file for manual review")
    args = parser.parse_args()

    corrections = load_corrections()
    print(f"Loaded {len(corrections)} corrections from HITL data")

    suggestions = generate_suggestions(corrections)
    print_suggestions(suggestions)

    if suggestions:
        # Save suggestions
        output_path = AUDIO_BASE_DIR / "_analysis" / "matcher_suggestions.json"
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w") as f:
            json.dump(suggestions, f, indent=2, ensure_ascii=False)
        print(f"\nSuggestions saved to: {output_path}")

        # Generate code patch
        patch = generate_code_patch(suggestions)
        patch_path = AUDIO_BASE_DIR / "_analysis" / "keyword_additions.py"
        with open(patch_path, "w") as f:
            f.write(patch)
        print(f"Code patch saved to: {patch_path}")
        print(f"\nReview the suggestions, then manually add them to voice/fuzzy_matcher.py KEYWORD_MAP.")


if __name__ == "__main__":
    main()
